### PR TITLE
Added support to exclude the properties in the search

### PR DESCRIPTION
**Pull request by prashantpimpale93**
Added support to exclude the properties while searching - #Fix-40

### CODE REVIEW

**Comment by aVolpe** [comment]
Since we now support filtering in nested objects, we need to be able to "exclude" the nested properties.

I think we can do this by passing a filtering the 'exclusionList' to the `checkInside` function and check there with `===`.

**Comment by prashantpimpale93** [comment]
@aVolpe Have added one more condition to the If block:

`excludes.includes(property)`

**Comment by aVolpe** [comment]
@prashantpimpale93 your test aren't passing in the latest version.

```js
Failures:
1) Pipe: Default Ignore the property in the search
  Message:
    Expected $.length = 2 to equal 1.
    Expected $[1] = Object({ a: Object({ b: 'e', c: Object({ b: 'd' }) }) }) to equal undefined.
  Stack:
    Error: Expected $.length = 2 to equal 1.
    Expected $[1] = Object({ a: Object({ b: 'e', c: Object({ b: 'd' }) }) }) to equal undefined.
        at UserContext.<anonymous> (/Users/arturovolpe/develop/avolpe/ng2-search-filter/src/ng2-filter.pipe.spec.ts:38:50)

5 specs, 1 failure
Finished in 0.021 seconds
```

Changing to this in the pipe seems to fix it:

```diff
           if (checkInside(item[property], term)) {
             return true;
           }
-        }
-        if (item[property].toString().toLowerCase().includes(toCompare)) {
+        } else if (item[property].toString().toLowerCase().includes(toCompare)) {
           return true;
         }

```

**Comment by prashantpimpale93** [comment]
@aVolpe okay will test it and commit again!

**Comment by prashantpimpale93** [comment]
@aVolpe Updated the code and committed! 

Have a look!

**Comment by prashantpimpale93** [comment]
@aVolpe Did you review the code changes?

**Comment by aVolpe** [comment]
I think the changes are a first aproach to the issue, maybe in a future we can add more complex filters like:

```js
"user.name", // to only filter  the name of the user
"user.ci*"
```

**Comment by prashantpimpale93** [comment]
@aVolpe Thanks a lot!

**Pull request merged**
