### PR TITLE
Remove postinstall script

### LINKED ISSUE #22: Upgrade to angular 5
Hi, i get this error when update myproject to angular5
**ng build --env=homolog -

Module build failed: Error: /var/www/html/.../node_modules/ng2-search-filter/src/ng2-filter.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/www/html/..../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/var/www/html/...../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ngfactory.js 80:0-63
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/ng2-search-filter/src/ng2-filter.pipe.ts
Module build failed: Error: /var/www/html/...../node_modules/ng2-search-filter/src/ng2-filter.pipe.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file se& ng build --env=homolog --prod  --aot ems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/www/html/..../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/var/www/html/....node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/dashboard/robot-instance/robot-instance.component.ngfactory.js 32:0-61
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

### PR DESCRIPTION
**Pull request by aVolpe**
fix #22

### CODE REVIEW

**Comment by pedro412** [comment]
hello there, thanks for the support,

when this is gonna be available? for download with npm?

i dowload the master branch but when npm install it says there is no"version": "0.4.2", 

or you know how can i fix that or install it manually ?

preciate the help thanks!

**Comment by solodynamo** [comment]
Hey @pedro412 version `0.4.2` is deployed, Check now.

**Comment by pedro412** [comment]
downloaded it and when trying to ng serve 
--------------------------------------------------
ERROR in ./node_modules/ng2-search-filter/index.ts
Module build failed: Error: C:\Users\admpalvarez\Desktop\encuesta\node_modules\ng2-search-filter\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admpalvarez\Desktop\encuesta\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:656:23)
    at plugin.done.then (C:\Users\admpalvarez\Desktop\encuesta\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/app.module.ts 25:26-54
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

ng -v
------------
Angular CLI: 1.6.4
Node: 9.3.0
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0



----------------------------

pakas

**Comment by solodynamo** [comment]
@aVolpe have a look into this.

**Comment by solodynamo** [comment]
@pedro412 the error corresponds to index.ts at root. I just merged a PR which removes not required files , Just give a try to `0.4.3`.

**Comment by pedro412** [comment]
Hi, this is what i got now 
-----------------------------
image


seems like there are missing files on the folder



hey, sorry to trouble you, im kind of new in all of this

**Comment by aVolpe** [comment]
@pedro412 please use the latest version `0.4.7`, that fix this issue.

**Comment by pedro412** [comment]
Its working now, Thank you guys =) 😍

**Comment by azharkrest** [comment]
ng build --prod it's giving error

ERROR in src\app\clothes-list\clothe-list\clothe-list.component.html(8,81): : Property 'filter' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(30,25): : Property 'filter' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(82,81): : Property 'filter' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(103,25): : Property 'filter' does not exist on
type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(8,81): : Property 'filter' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(82,81): : Property 'filter' does not exist on type 'ClotheListComponent'.


D:\Working\RFIDangularCRUD> ng build --prod
 10% building modules 4/6 modules 2 active ...\bootstrap\dist\css\bootstrap.min.cssNode#moveTo was deprecated. Use Container#append.
Date: 2018-03-05T09:44:21.114Z
Hash: c17f1869cea1206cc0aa
Time: 23261ms
chunk {0} styles.79dff28f100b6025a8c3.bundle.css (styles) 328 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.5146cff1dff3f8e8b838.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in src\app\clothes-list\clothe-list\clothe-list.component.html(8,81): : Property 'term' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(28,25): : Property 'term' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(65,81): : Property 'term' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(86,25): : Property 'term' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(8,81): : Property 'term' does not exist on type 'ClotheListComponent'.
src\app\clothes-list\clothe-list\clothe-list.component.html(65,81): : Property 'term' does not exist on type 'ClotheListComponent'.

**Comment by aVolpe** [comment]
@azharkrest please, show us your `clothe-list.component.html` file. It's seems that you don't has a property "term" in your controller,

**Comment by azharkrest** [comment]
@ aVolpe -- Thanks for the comment.
 I am using filter pagination in the same project on local it is working fine but when I am building with the help of ng build --prod it gives me error .
Error which  I got after running ng build --prod
ngbuild_error

HTML file ---->

<tabs >
    <form class="clothlist-form" #clothListForm="ngForm">
        <tab tabTitle="Pending"  >
            <div class="col-md-12" style="padding-right:50px; padding-left:50px; ">
                <div class="col-md-4">    
                    <nav class="navbar">
                       <input class="form-control" type="text" name="search" [(ngModel)]="filter1" placeholder="Search"> 
                    </nav>
                </div>  
                <br/>
                  
                <table class="table table-responsive table-striped table-bordered table-sm table-hover">
                    <thead >
                        <tr style="background-color:#cf041b; color:aliceblue; text-align:center">
                            <th (click)="sort('OrderNo')">Order #</th>
                            <th (click)="sort('ModelName')">Model Name</th>
                            <th (click)="sort('Color')">Color</th>
                            <th (click)="sort('Size')">Size</th>
                            <th (click)="sort('ClotheBarcodeNo')">Clothe Barcode #</th>
                            <th (click)="sort('Quantity')">Quantity</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody style="background-color:white; color:black; text-align:center">
                        <tr *ngFor="let clotheList of clothesListListForPending | filter:filter1 |orderBy: key : reverse| paginate: { itemsPerPage: 10, currentPage: p,id: 'first' }; let i = index"> 
                            <td style="text-align:center">{{clotheList.OrderNo}}</td>
                            <td>{{clotheList.ModelName}}</td>
                            <td>{{clotheList.Color}}</td>
                            <td style="text-align:center">  {{clotheList.Size}}</td>
                            <td style="text-align:center"> {{clotheList.ClotheBarcodeNo}}</td>
                            <td style="text-align:center"> {{clotheList.Quantity}}</td>
                            <td> <input type="checkbox" 
                                name="{{clotheList.ClotheId}}" 
                                value="{{clotheList.ClotheId}}"
                                (change)="change($event, clotheList.ClotheId,clotheList.checked)"
                                [(ngModel)]="clotheList.checked">
                         
                            </td>
                     
                        </tr>
                    </tbody>
                    <br/>
                    <div style="text-align:center;">
                        <button type="submit" class="btn btn-sm btn-primary" (click)="print(clothListForm)" >Print</button>
                    </div>
                </table> 
                  
                <pagination-controls (pageChange)="p = $event"  id="first" style="text-align:center; color:white"></pagination-controls>
                  
            </div>
       
        </tab>
    </form> 
    <tab tabTitle="Printed">
        <div class="col-md-12" style="padding-right:50px; padding-left:50px">
            <div class="col-md-4">    
                <nav class="navbar">
                    <input class="form-control" type="text" name="search" [(ngModel)]="filter2" placeholder="Search">
                </nav>
            </div>  
            <br/>
                  
            <table class="table table-responsive table-striped table-bordered table-sm table-hover center" >
                <thead >
                    <tr style="background-color:#0f975c; color:aliceblue; text-align:center">
                        <th (click)="sort('OrderNo')">Order #</th>
                        <th (click)="sort('ModelName')">Model Name</th>
                        <th (click)="sort('Color')">Color</th>
                        <th (click)="sort('Size')">Size</th>
                        <th (click)="sort('ClotheBarcodeNo')">Clothe Barcode #</th>
                        <th (click)="sort('Quantity')">Quantity</th>
                    </tr>
                </thead>
                <tbody style="background-color:white; color:black; text-align:center">
                    <tr *ngFor="let clotheList of clothesListListForPrinted | filter:filter2 | orderBy: key : reverse| paginate: { itemsPerPage: 10, currentPage: p1, id: 'second'  }; let i = index">
                        <td style="text-align:center">{{clotheList.OrderNo}}</td>
                        <td>{{clotheList.ModelName}}</td>
                        <td>{{clotheList.Color}}</td>
                        <td style="text-align:center">{{clotheList.Size}}</td>
                        <td style="text-align:center"> {{clotheList.ClotheBarcodeNo}}</td>
                        <td style="text-align:center"> {{clotheList.Quantity}}</td>
                    </tr>
                </tbody>
                
            </table> 
                <pagination-controls (pageChange)="p1 = $event" id="second" style="text-align:center;color:white"></pagination-controls>
        </div>
    </tab>

<tabs>
  
      
     Can you please suggest why filter is giving the problem.

**Comment by aVolpe** [comment]
You need to declare the var in your `ts` file, like this:

`export class ClotheListComponent {
    // other fields
    public filter1: string;
    // constructor and methods
}`

The issue is not with the plugin itselft, but with Angular, when you compile
your `html` code is converted to `ts` code, and the _implicit_ variables, 
like `filter` in your case, are not compiled.

Also, I don't see where the input for filter1 is.

**Comment by azharkrest** [comment]
@aVolpe Thanks for your valuable feedback. Now it's working.

**Comment by azharkrest** [comment]
I have design login page by default it is assign left, in mobile view it shows in center. But when I apply css it in web view it comes in center but in mobile view it doesn't.

**Comment by aVolpe** [comment]
@azharkrest please post question like that in StackOverflow, so we can keep this issue tracker limited to the plugin.

If you ask in stackoverflow and send me the link I will help you, please post your html and css too.

**Pull request merged**
