### PR TITLE
Angular 5 ng packagr

### PR DESCRIPTION
**Pull request by aVolpe**
This is the fist step to provide support for angular5

This PR also add some test and fixes some unrelated issues.

### CODE REVIEW

**Comment by solodynamo** [comment]
Changes looks fine . I was thinking of a new release after this PR is merged and I wish we could also integrate search on particular property after this angular 5 support version release(https://github.com/solodynamo/ng2-search-filter/issues/15) as you suggested method looks great. Do resolve the conflicts though.

**Comment by solodynamo** [comment]
Hey @aVolpe i hope you have also tested the changes on an example so that it not breaks builds of other users of the package.

**Comment by aVolpe** [comment]
@solodynamo Yes, I test as a standalone package, I was thinking of adding that as a new "integration test", but I can't make this project to run any compex test.

I will try later this week again!.

**Comment by solodynamo** [comment]
@aVolpe awesome merging it and making a new release.

**Pull request merged**
